/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Session.session;
import config.koneksi;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Level;

public class UserTickets extends javax.swing.JFrame {

    /**
     * Creates new form UserTickets
     */
    private Connection conn;

    public UserTickets() {
        initComponents();
        conn = koneksi.getConnection();
        getData();
        nonAktif();
    }

    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);
        int customerId = session.getuserId();
        String name = session.getName();
        user.setText(name);
        try {
            String sql = "SELECT t.id, t.user_id, t.flight_id, t.ticket_number, t.booking_time, "
                    + "f.flight_number, f.departure, f.destination, f.departure_time, f.arrival_time, f.price "
                    + "FROM tickets t "
                    + "JOIN flights f ON t.flight_id = f.id "
                    + "WHERE t.flight_id = f.id AND t.user_id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, customerId);
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while (rs.next()) {
                int ticket_id = rs.getInt("id");
                String ticket_num = rs.getString("ticket_number");
                String flightNumber = rs.getString("flight_number");
                String departure = rs.getString("departure");
                String destination = rs.getString("destination");
                String departure_time = rs.getString("departure_time");
                String arrival_time = rs.getString("arrival_time");
                int price = rs.getInt("price");

                Object[] row = {no, ticket_id, ticket_num, flightNumber, departure, destination, departure_time, arrival_time, price};
                model.addRow(row);
                no++;
            }
            ps.close();
            rs.close();

        } catch (SQLException e) {
            Logger.getLogger(UserDashboardForm.class.getName()).log(Level.SEVERE, "Terjadi Kesalahan Pada Database", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat pesanan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        destinasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        waktu_keberangkatan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        n_penerbangan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        keberangkatan = new javax.swing.JTextField();
        harga_tiket = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        waktu_kedatangan = new javax.swing.JTextField();
        qrCode = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        no_tiket = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        user.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        user.setText("User");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Ticket", "Nomor Tiket", "Nomor Penerbangan", "Keberangkatan", "Destinasi", "Waktu Keberangkatan", "Waktu Kedatangan", "Harga Tiket"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_data.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_data.setRowHeight(40);
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        jLabel8.setText("Search");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("TIKET SAYA");

        user1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        user1.setText("Hi,");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Detail Tiket");

        logout1.setText("Kembali Ke Halaman Utama");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Destinasi");

        destinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinasiActionPerformed(evt);
            }
        });

        jLabel6.setText("Waktu Keberangkatan");

        waktu_keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktu_keberangkatanActionPerformed(evt);
            }
        });

        jLabel4.setText("Nomor Penerbangan");

        n_penerbangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_penerbanganActionPerformed(evt);
            }
        });

        jLabel7.setText("Keberangkatan");

        keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keberangkatanActionPerformed(evt);
            }
        });

        harga_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_tiketActionPerformed(evt);
            }
        });

        jLabel12.setText("Harga Tiket");

        jLabel13.setText("Waktu Kedatangan");

        waktu_kedatangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktu_kedatanganActionPerformed(evt);
            }
        });

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel9.setText("Nomor Tiket");

        no_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_tiketActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(keberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(destinasi)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(n_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(waktu_keberangkatan, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))
                                    .addComponent(no_tiket)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(56, 56, 56)
                                            .addComponent(jLabel12))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btn_clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(waktu_kedatangan, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(harga_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qrCode)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(300, 300, 300))
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(user1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(user))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user)
                            .addComponent(user1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(qrCode)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(no_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(n_penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(waktu_keberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(keberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(destinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(28, 28, 28)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(harga_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(waktu_kedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        session.logout();
        LoginForm login = new LoginForm();
        login.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(this, "Berhasil Logout");
    }//GEN-LAST:event_logoutActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_data.getSelectedRow();
        if (selectedRow != -1) {
            String ticketN = tbl_data.getValueAt(selectedRow, 2).toString();
            String flightN = tbl_data.getValueAt(selectedRow, 3).toString();
            String departure = tbl_data.getValueAt(selectedRow, 4).toString();
            String destination = tbl_data.getValueAt(selectedRow, 5).toString();
            String departure_time = tbl_data.getValueAt(selectedRow, 6).toString();
            String arrival_time = tbl_data.getValueAt(selectedRow, 7).toString();
            String price = tbl_data.getValueAt(selectedRow, 8).toString();

            no_tiket.setText(ticketN);
            n_penerbangan.setText(flightN);
            keberangkatan.setText(departure);
            destinasi.setText(destination);
            waktu_keberangkatan.setText(departure_time);
            waktu_kedatangan.setText(arrival_time);
            harga_tiket.setText(price);
            btn_delete.setEnabled(true);
        }
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_data.getModel();
        model.setRowCount(0);

        String cari = search.getText();
        int customerId = session.getuserId();

        try {
            String sql = "SELECT t.id, t.user_id, t.flight_id, t.ticket_number, t.booking_time, "
                    + "f.flight_number, f.departure, f.destination, f.departure_time, f.arrival_time, f.price "
                    + "FROM tickets t "
                    + "JOIN flights f ON t.flight_id = f.id "
                    + "WHERE t.flight_id = f.id AND t.user_id = ? AND (ticket_number LIKE ? OR flight_number LIKE ? OR departure LIKE ? OR destination LIKE ? OR departure_time LIKE ? OR arrival_time LIKE ? OR price LIKE ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, customerId);
            String cariWildcard = "%" + cari + "%";
            for (int i = 2; i <= 8; i++) {
                ps.setString(i, cariWildcard);
            }
            ResultSet rs = ps.executeQuery();

            int no = 1;

            while (rs.next()) {
                int ticketId = rs.getInt("id");
                String ticket_num = rs.getString("ticket_number");
                String flightNumber = rs.getString("flight_number");
                String departure = rs.getString("departure");
                String destination = rs.getString("destination");
                String departure_time = rs.getString("departure_time");
                String arrival_time = rs.getString("arrival_time");
                int price = rs.getInt("price");

                Object[] row = {no,ticketId, ticket_num, flightNumber, departure, destination, departure_time, arrival_time, price};
                model.addRow(row);
                no++;
            }
            ps.close();
            rs.close();

        } catch (SQLException e) {
            Logger.getLogger(UserDashboardForm.class.getName()).log(Level.SEVERE, "Koneksi ke database gagal", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat Jadwal Penerbangan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchKeyTyped

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        new UserDashboardForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout1ActionPerformed

    private void destinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinasiActionPerformed

    private void waktu_keberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktu_keberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktu_keberangkatanActionPerformed

    private void n_penerbanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_penerbanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_penerbanganActionPerformed

    private void keberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keberangkatanActionPerformed

    private void harga_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_tiketActionPerformed

    private void waktu_kedatanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktu_kedatanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktu_kedatanganActionPerformed

    private void no_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_tiketActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        reset();
        getData();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_data.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Baris yang akan diperbarui");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapus Data ini ? ", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            
            String ticket_id = tbl_data.getValueAt(selectedRow, 1).toString();
            String ticket_number = tbl_data.getValueAt(selectedRow, 2).toString();

            try {
                String sql = "DELETE FROM payments WHERE ticket_id = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, ticket_id);

                int rowDelete = st.executeUpdate();
                if (rowDelete > 0) {

                    String sql1 = "DELETE FROM tickets WHERE ticket_number = ?";
                    PreparedStatement st1 = conn.prepareStatement(sql1);
                    st1.setString(1, ticket_number);

                    int rowDelete1 = st1.executeUpdate();
                    
                    if(rowDelete1 > 0) {
                        JOptionPane.showMessageDialog(this, "Tiket Berhasil Dihapus");
                    } else {
                        JOptionPane.showMessageDialog(this, "Tiket Gagal Dihapus");
                    }
                    st1.close();
                }

                st.close();
            } catch (SQLException e) {
                Logger.getLogger(UserTickets.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        reset();
        getData();
        nonAktif();
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JTextField destinasi;
    private javax.swing.JTextField harga_tiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keberangkatan;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JTextField n_penerbangan;
    private javax.swing.JTextField no_tiket;
    private javax.swing.JLabel qrCode;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbl_data;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JTextField waktu_keberangkatan;
    private javax.swing.JTextField waktu_kedatangan;
    // End of variables declaration//GEN-END:variables

    private void nonAktif() {
        keberangkatan.setEnabled(false);
        n_penerbangan.setEnabled(false);
        waktu_keberangkatan.setEnabled(false);
        waktu_kedatangan.setEnabled(false);
        destinasi.setEnabled(false);
        harga_tiket.setEnabled(false);
        no_tiket.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    private void reset() {
        search.setText("");
        keberangkatan.setText("");
        n_penerbangan.setText("");
        waktu_keberangkatan.setText("");
        waktu_kedatangan.setText("");
        destinasi.setText("");
        harga_tiket.setText("");
        no_tiket.setText("");
        qrCode.setText("");
        btn_delete.setEnabled(false);
    }
}
